name: Deploy to Cloud Run

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  PROJECT_ID: bud-next-hackathon
  SERVICE_NAME: bud-next-app
  REGION: asia-northeast1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        
    - name: Configure Docker to use gcloud as a credential helper
      run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      
    - name: Build and push Docker image
      run: |
        docker build -f Dockerfile.production -t asia-northeast1-docker.pkg.dev/$PROJECT_ID/bud-repo/$SERVICE_NAME:$GITHUB_SHA .
        docker push asia-northeast1-docker.pkg.dev/$PROJECT_ID/bud-repo/$SERVICE_NAME:$GITHUB_SHA
        
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image asia-northeast1-docker.pkg.dev/$PROJECT_ID/bud-repo/$SERVICE_NAME:$GITHUB_SHA \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --port 8000 \
          --memory 1Gi \
          --cpu 1X
